/radar2023:
  EnemyType: 0 # 0 RED 1 BLUE
  AuthPassword: "momoko11" # 用户密码，用于串口权限
  CameraConfig0: "Config_0.SJTU.Config" # 相机图像配置文件名称
  CameraConfig1: "Config_1.SJTU.Config" # 相机图像配置文件名称
  TestVideo: "SJTU.mp4" # 测试视频名称
  CameraParam0: "camera0.SJTU.yaml" # 外参文件
  CameraParam1: "camera1.SJTU.yaml" # 外参文件
  OnnxForArmor: "Armor.onnx" # 装甲板转换用Onnx模型
  OnnxForCar: "Car.onnx" # 车辆转换用Onnx模型
  EngineForArmor: "Armor.engine" # 生成的装甲板识别用TRT模型
  EngineForCar: "Car.engine" # 生成的车辆识别用TRT模型
  OnnxForSort: "" # Sort使用的Onnx模型
  EngineForSort: "" # Sort使用的TRT模型
  SerialPortName: "/dev/ttyUSB0" # 串口地址

/gui:
  MapRMUC: "map.jpg" # 地图文件名
  CoverDepth: false # 是否默认启用深度图覆盖